apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: "docker image image"
          image: oluwaseun7/dmailer:latest
          ports:
            - containerPort: 3001
