apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: "docker image image"
          image: oluwaseun7/dmailer:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /
              port: 3001
          plifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
            preStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]

