apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test4
  template:
    metadata:
      labels:
        app: test4
    spec:
      containers:
        - name: docker-image
          image: oluwaseun7/dmailer:1.0.1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"          
          ports:
            - containerPort: 3001
